# Image dir
image_dir: './data/VOCtest/JPEGImages/000001.jpg'

#image_dir: 'C:/Users/admin/Desktop/Git_Repo/TF/yolov3/data/VOCtest/JPEGImages/000001.jpg'

# Select the scale
scale: 1

# The path of the target image to save
save_dir: './generated_images'

# Out put image attribute
image_width: 128
image_height: 128